(()=>{
let data=JSON.parse(JSON.stringify(window.MENU_DATA));
let currentIndex=0,currentType="food",pendingUploadedImageData=null,adminSearchTerm="";
const edited={food:new Set(),beverages:new Set(),chef:new Set()};
const $=id=>document.getElementById(id);
const foodCategories=[["couvert","Couvert"],["starters","Entradas"],["vegetarian","Vegetariano"],["fish","Peixes"],["meat","Carnes"],["desserts","Sobremesas"]];
const chefTypes=[["Entrada","Entrada"],["Peixe","Peixe"],["Carne","Carne"]];
const beverageCategories=[["wine_green_white","Vinhos · Brancos · Verdes"],["wine_white","Vinhos · Brancos · Maduros"],["wine_green_red","Vinhos · Tintos · Verdes"],["wine_red","Vinhos · Tintos · Maduros"],["rose","Vinhos · Rosé"],["sparkling","Espumantes"],["soft","Águas e Refrigerantes"],["beer","Cervejas"],["sangria","Sangrias"],["digestif","Aperitivos / Digestivos"],["hot","Quentes"]];
function categoryOptions(){return currentType==="food"?foodCategories:currentType==="beverages"?beverageCategories:chefTypes}
function categoryLabel(k){const f=[...foodCategories,...beverageCategories].find(x=>x[0]===k);return f?f[1]:k}
function setPublishState(text,kind=""){const el=$("publishState");if(!el)return;el.textContent=text;el.className="publish-state"+(kind?" "+kind:"")}
function renderHead(){$("tableHead").innerHTML=currentType==="food"?"<tr><th>ID</th><th>Nome</th><th>Categoria</th><th>Preço</th><th>Disponível</th></tr>":currentType==="beverages"?"<tr><th>Nome</th><th>Categoria</th><th>Região</th><th>Garrafa</th><th>Copo</th></tr>":"<tr><th>ID</th><th>Tipo</th><th>Nome PT</th><th>Preço</th><th>Disponível</th></tr>"}
function normalizeSearchText(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function searchableText(x){const n=x?.name&&typeof x.name==="object"?Object.values(x.name):[x?.name],d=x?.description&&typeof x.description==="object"?Object.values(x.description):[x?.description];return normalizeSearchText([x?.code,x?.id,x?.type,x?.category,categoryLabel(x?.category),x?.region,...n,...d,...(x?.tags||[]),...(x?.allergens||[])].filter(Boolean).join(" "))}
function renderRows(){renderHead();let arr=currentType==="food"?data.food:currentType==="beverages"?data.beverages:(data.chefSuggestion?.items||[]);const term=normalizeSearchText(adminSearchTerm),visible=arr.map((x,i)=>({x,i})).filter(({x})=>!term||searchableText(x).includes(term));const result=$("adminSearchResult");if(result)result.textContent=term?`${visible.length} resultado${visible.length===1?"":"s"} de ${arr.length}`:`${arr.length} item${arr.length===1?"":"s"}`;if(!visible.length){$("rows").innerHTML='<tr><td colspan="6" class="admin-no-results">Nenhum item encontrado.</td></tr>';return}$("rows").innerHTML=visible.map(({x,i})=>{const c=edited[currentType].has(i)?" edited-row":"";if(currentType==="food")return `<tr class="${c}" data-i="${i}"><td>${x.code||""}</td><td>${x.name?.pt||""}</td><td>${categoryLabel(x.category)}</td><td>${Number(x.price||0).toFixed(2)} €</td><td>${x.available===false?"Não":"Sim"}</td></tr>`;if(currentType==="beverages")return `<tr class="${c}" data-i="${i}"><td>${x.name||""}</td><td>${categoryLabel(x.category)}</td><td>${x.region||""}</td><td>${Number(x.bottle||0).toFixed(2)} €</td><td>${x.glass?Number(x.glass).toFixed(2)+" €":"—"}</td></tr>`;return `<tr class="${c}" data-i="${i}"><td>${x.id||""}</td><td>${x.type||""}</td><td>${x.name?.pt||""}</td><td>${Number(x.price||0).toFixed(2)} €</td><td>${x.available===false?"Não":"Sim"}</td></tr>`}).join("");document.querySelectorAll("#rows tr[data-i]").forEach(r=>r.onclick=()=>openEditor(+r.dataset.i))}
function fillCategorySelect(s){$("category").innerHTML=categoryOptions().map(([v,l])=>`<option value="${v}" ${v===s?"selected":""}>${l}</option>`).join("")}
function setFieldVisibility(){const f=currentType==="food",b=currentType==="beverages",c=currentType==="chef";$("descriptionField").style.display=(f||c)?"flex":"none";$("allergensField").style.display=f?"flex":"none";$("tagsField").style.display=f?"flex":"none";$("featuredField").style.display=f?"flex":"none";$("regionField").style.display=b?"flex":"none";$("glassField").style.display=b?"flex":"none"}
function openEditor(i){currentIndex=i;setFieldVisibility();const x=currentType==="food"?data.food[i]:currentType==="beverages"?data.beverages[i]:data.chefSuggestion.items[i];fillCategorySelect(currentType==="chef"?x.type:x.category);$("available").checked=x.available!==false;$("modalTitle").textContent=currentType==="food"?"Editar prato":currentType==="beverages"?"Editar bebida":"Editar Sugestão do Chefe";$("code").parentElement.style.display=currentType==="beverages"?"none":"flex";$("code").value=x.code||x.id||"";$("name_pt").value=currentType==="beverages"?(x.name||""):(x.name?.pt||"");$("desc_pt").value=currentType==="beverages"?"":(x.description?.pt||"");$("price").value=currentType==="beverages"?(x.bottle??""):(x.price??"");$("glass").value=x.glass??"";$("region").value=x.region||"";$("image").value=x.image||"";$("allergens").value=(x.allergens||[]).join(", ");$("tags").value=(x.tags||[]).join(", ");$("featured").checked=!!x.featured;$("imageUpload").value="";pendingUploadedImageData=null;preview();setPublishState("");$("editorModal").classList.add("open");$("editorModal").setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeEditor(){$("editorModal").classList.remove("open");$("editorModal").setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
function preview(){$("preview").src=pendingUploadedImageData||$("image").value||(currentType==="beverages"?"assets/drink-placeholder.svg":"assets/dish-placeholder.svg");$("preview").onerror=()=>{$("preview").src=currentType==="beverages"?"assets/drink-placeholder.svg":"assets/dish-placeholder.svg"}}
$("image").oninput=()=>{pendingUploadedImageData=null;preview()};
function safeImageFileName(n){const r=(n||"fotografia").replace(/\.[^.]+$/,"");return (r.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"")||"fotografia")+".jpg"}
async function fileToOptimizedDataUrl(file){if(!file||!file.type.startsWith("image/"))throw new Error("O ficheiro selecionado não é uma imagem.");const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Não foi possível ler a imagem."));r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const e=new Image();e.onload=()=>res(e);e.onerror=()=>rej(new Error("Não foi possível abrir a imagem."));e.src=dataUrl});const max=1600;let w=img.naturalWidth,h=img.naturalHeight;if(Math.max(w,h)>max){const s=max/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);return c.toDataURL("image/jpeg",.86)}
$("imageUpload").onchange=async()=>{const f=$("imageUpload").files?.[0];if(!f)return;try{pendingUploadedImageData=await fileToOptimizedDataUrl(f);$("image").value="assets/dishes/"+safeImageFileName(f.name);preview();setPublishState("Fotografia pronta para publicar.")}catch(e){setPublishState(e.message||"Não foi possível carregar a imagem.","error");$("imageUpload").value=""}};
$("clearUploadedImage").onclick=()=>{$("imageUpload").value="";$("image").value="";pendingUploadedImageData=null;preview();setPublishState("")};
$("closeModal").onclick=closeEditor;$("cancelModal").onclick=closeEditor;$("editorModal").addEventListener("click",e=>{if(e.target===$("editorModal"))closeEditor()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("editorModal").classList.contains("open"))closeEditor()});
document.querySelectorAll(".admin-tab").forEach(btn=>btn.onclick=()=>{currentType=btn.dataset.type;document.querySelectorAll(".admin-tab").forEach(b=>b.classList.toggle("active",b===btn));refreshChefSettings();renderRows()});
function refreshChefSettings(){const c=currentType==="chef";$("chefAdminSettings").hidden=!c;if(c){data.chefSuggestion=data.chefSuggestion||{enabled:true,validUntil:"",items:[]};$("chefEnabled").checked=data.chefSuggestion.enabled!==false;$("chefValidUntil").value=data.chefSuggestion.validUntil||""}}
$("chefEnabled").onchange=()=>{data.chefSuggestion.enabled=$("chefEnabled").checked};
$("chefValidUntil").onchange=()=>{data.chefSuggestion.validUntil=$("chefValidUntil").value};
$("addChefItem").onclick=()=>{data.chefSuggestion=data.chefSuggestion||{enabled:true,validUntil:"",items:[]};data.chefSuggestion.items.push({id:"CHEF-"+String(data.chefSuggestion.items.length+1).padStart(2,"0"),type:"Entrada",name:{pt:"Nova sugestão",en:"",fr:"",es:"",de:"",it:"",ru:""},description:{pt:"",en:"",fr:"",es:"",de:"",it:"",ru:""},price:0,image:"",available:true});edited.chef.add(data.chefSuggestion.items.length-1);renderRows();openEditor(data.chefSuggestion.items.length-1)};
refreshChefSettings();renderRows();const adminSearch=$("adminSearch"),clearAdminSearch=$("clearAdminSearch");if(adminSearch){adminSearch.addEventListener("input",()=>{adminSearchTerm=adminSearch.value;clearAdminSearch?.classList.toggle("is-visible",!!adminSearchTerm);renderRows()});adminSearch.addEventListener("keydown",e=>{if(e.key==="Escape"&&adminSearch.value){adminSearch.value="";adminSearchTerm="";clearAdminSearch?.classList.remove("is-visible");renderRows()}})}if(clearAdminSearch)clearAdminSearch.addEventListener("click",()=>{adminSearch.value="";adminSearchTerm="";clearAdminSearch.classList.remove("is-visible");renderRows();adminSearch.focus()});
})();