(async()=>{
  const WORKER_DATA_URL="https://colherdpau-admin-api.joao-c-veloso93.workers.dev/menu-data";
  let data=window.MENU_DATA;
  const params=new URLSearchParams(location.search);
  const lang=params.get("lang")||"pt";
  let type="food",cat="all";
  const $=id=>document.getElementById(id);
  const euro=v=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(v);
  const labels={pt:{food:"Comida",drinks:"Bebidas",all:"Todos",title:"A nossa carta",sub:"Sabores portugueses, à sua mesa.",introText:"O melhor início para uma grande refeição."},en:{food:"Food",drinks:"Drinks",all:"All",title:"Our menu",sub:"Portuguese flavours, at your table.",introText:"The perfect beginning to a great meal."},fr:{food:"Plats",drinks:"Boissons",all:"Tous",title:"Notre carte",sub:"Saveurs portugaises, à votre table.",introText:"Le meilleur début pour un excellent repas."},es:{food:"Comida",drinks:"Bebidas",all:"Todos",title:"Nuestra carta",sub:"Sabores portugueses, en su mesa.",introText:"El mejor comienzo para una gran comida."},de:{food:"Speisen",drinks:"Getränke",all:"Alle",title:"Unsere Speisekarte",sub:"Portugiesische Aromen, an Ihrem Tisch.",introText:"Der beste Start in ein großartiges Essen."},it:{food:"Cibo",drinks:"Bevande",all:"Tutti",title:"Il nostro menu",sub:"Sapori portoghesi, alla vostra tavola.",introText:"Il miglior inizio per un ottimo pasto."},ru:{food:"Еда",drinks:"Напитки",all:"Все",title:"Наше меню",sub:"Португальские вкусы к вашему столу.",introText:"Лучшее начало отличной трапезы."}};
  const L=labels[lang]||labels.pt;
  const chefTitleParts={pt:{main:"SUGESTÃO",script:"do Chefe"},en:{main:"CHEF'S",script:"Suggestion"},fr:{main:"SUGGESTION",script:"du Chef"},es:{main:"SUGERENCIA",script:"del Chef"},de:{main:"EMPFEHLUNG",script:"des Küchenchefs"},it:{main:"SUGGERIMENTO",script:"dello Chef"},ru:{main:"РЕКОМЕНДАЦИЯ",script:"шеф-повара"}};
  const foodCats={couvert:"Couvert",starters:{pt:"Entradas",en:"Starters",fr:"Entrées",es:"Entradas",de:"Vorspeisen",it:"Antipasti",ru:"Закуски"}[lang]||"Entradas",vegetarian:{pt:"Vegetariano",en:"Vegetarian",fr:"Végétarien",es:"Vegetariano",de:"Vegetarisch",it:"Vegetariano",ru:"Вегетарианские блюда"}[lang]||"Vegetariano",fish:{pt:"Peixes",en:"Fish",fr:"Poissons",es:"Pescado",de:"Fisch",it:"Pesce",ru:"Рыбные блюда"}[lang]||"Peixes",meat:{pt:"Carnes",en:"Meat",fr:"Viandes",es:"Carne",de:"Fleisch",it:"Carne",ru:"Мясные блюда"}[lang]||"Carnes",desserts:{pt:"Sobremesas",en:"Desserts",fr:"Desserts",es:"Postres",de:"Nachtisch",it:"Dessert",ru:"Десерты"}[lang]||"Sobremesas"};
  const drinkCats={wine_green_white:"Vinhos Verdes Brancos",wine_white:"Vinhos Maduros Brancos",wine_green_red:"Vinhos Verdes Tintos",wine_red:"Vinhos Maduros Tintos",rose:"Vinhos Rosé",sparkling:"Espumantes",soft:"Águas e Refrigerantes",beer:"Cervejas",sangria:"Sangrias",digestif:"Aperitivos / Digestivos",hot:"Quentes"};
  const cats={...foodCats,...drinkCats};
  const escapeAttr=s=>String(s||"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");

  async function loadFreshData(){try{const res=await fetch(WORKER_DATA_URL+"?_="+Date.now(),{cache:"no-store"});const body=await res.json();if(!res.ok||!body?.ok||!body?.data)throw new Error(body?.error||"Dados indisponíveis");data=body.data;window.MENU_DATA=body.data;return true}catch(e){console.warn("A usar dados locais da carta porque não foi possível obter a versão mais recente.",e);return false}}
  function applyHeader(){$("pageTitle").textContent=L.title;$("pageSubtitle").textContent=L.sub;$("foodBtn").textContent=L.food;$("drinkBtn").textContent=L.drinks;document.querySelectorAll(".menu-language-flags a").forEach(a=>a.classList.toggle("active",a.dataset.lang===lang))}
  function renderChefSuggestion(){const section=$("chefSuggestion");if(type!=="food"){section.hidden=true;return}const block=data.chefSuggestion;if(!block||block.enabled===false){section.hidden=true;return}const items=(block.items||[]).filter(x=>x.available!==false);if(!items.length){section.hidden=true;return}section.hidden=false;const parts=chefTitleParts[lang]||chefTitleParts.pt;$("chefTitleMain").textContent=parts.main;$("chefTitleScript").textContent=parts.script;const typeLabels={Entrada:{pt:"ENTRADA",en:"STARTER",fr:"ENTRÉE",es:"ENTRADA",de:"VORSPEISE",it:"ANTIPASTO",ru:"ЗАКУСКА"},Peixe:{pt:"PEIXE",en:"FISH",fr:"POISSON",es:"PESCADO",de:"FISCH",it:"PESCE",ru:"РЫБА"},Carne:{pt:"CARNE",en:"MEAT",fr:"VIANDE",es:"CARNE",de:"FLEISCH",it:"CARNE",ru:"МЯСО"}};$("chefGrid").innerHTML=items.map(item=>{const name=item.name?.[lang]||item.name?.pt||"",desc=item.description?.[lang]||item.description?.pt||"",itemType=typeLabels[item.type]?.[lang]||item.type||"",image=item.image||"assets/dish-placeholder.svg";return `<article class="chef-card"><div class="chef-card-header"><span class="chef-type">${itemType}</span><h3>${name}</h3></div><div class="chef-image-wrap"><img class="chef-image zoomable" src="${image}" data-full="${image}" data-caption="${escapeAttr(name)}" alt="${escapeAttr(name)}" onerror="this.onerror=null;this.src='assets/dish-placeholder.svg'"><div class="chef-price">${euro(item.price)}</div></div><div class="chef-card-body"><p>${desc}</p></div></article>`}).join("");wireImageZoom()}
  function renderCats(){const arr=type==="food"?data.food:data.beverages;const ks=[...new Set(arr.filter(x=>x.available!==false).map(x=>x.category))];$("categoryStrip").innerHTML=[["all",L.all],...ks.map(k=>[k,cats[k]||k])].map(([k,n])=>`<button class="cat-btn ${cat===k?"active":""}" data-c="${k}">${n}</button>`).join("");document.querySelectorAll("#categoryStrip .cat-btn").forEach(b=>b.onclick=()=>{cat=b.dataset.c;renderCats();renderMenu()})}
  function renderMenu(){const arr=(type==="food"?data.food:data.beverages).filter(x=>x.available!==false&&(cat==="all"||x.category===cat)),grouped={};arr.forEach(x=>(grouped[x.category]??=[]).push(x));$("menuContent").innerHTML=Object.entries(grouped).map(([k,items],idx)=>{const rows=items.map(x=>{if(type==="food"){const name=x.name?.[lang]||x.name?.pt||"",desc=x.description?.[lang]||x.description?.pt||"",image=x.image||"assets/dish-placeholder.svg";return `<article class="dish"><img class="dish-image zoomable" src="${image}" onerror="this.onerror=null;this.src='assets/dish-placeholder.svg'" alt="${escapeAttr(name)}" data-full="${image}" data-caption="${escapeAttr(name)}"><div><h3>${name}</h3>${desc?`<p>${desc}</p>`:""}</div><div class="price">${euro(x.price)}</div></article>`}const image=x.image||"assets/drink-placeholder.svg";return `<article class="dish"><img class="dish-image drink-image zoomable" src="${image}" onerror="this.onerror=null;this.src='assets/drink-placeholder.svg'" alt="${escapeAttr(x.name)}" data-full="${image}" data-caption="${escapeAttr(x.name)}"><div><h3>${x.name}</h3>${x.region?`<p>${x.region}</p>`:""}</div><div class="price">${euro(x.bottle)}${x.glass?`<div class="tiny">Copo ${euro(x.glass)}</div>`:""}</div></article>`}).join("");return `<section class="section ${idx===0?"first-menu-section":""}"><div class="section-heading"><h2>${cats[k]||k}</h2>${idx===0&&type==="food"?`<span>${L.introText}</span><i></i>`:""}</div>${rows}</section>`}).join("");wireImageZoom()}
  function wireImageZoom(){document.querySelectorAll(".zoomable").forEach(img=>{if(img.dataset.zoomBound==="1")return;img.dataset.zoomBound="1";img.onclick=()=>{$("lightboxImage").src=img.dataset.full||img.src;$("lightboxCaption").textContent=img.dataset.caption||img.alt||"";$("imageLightbox").classList.add("open");document.body.classList.add("modal-open")}})}
  const scrollToMenuArea=()=>{const target=$("menuArea");if(!target)return;window.scrollTo({top:target.getBoundingClientRect().top+window.scrollY-24,behavior:"smooth"})};
  $("foodBtn").onclick=()=>{type="food";cat="all";$("foodBtn").classList.add("active");$("drinkBtn").classList.remove("active");renderChefSuggestion();renderCats();renderMenu();requestAnimationFrame(()=>requestAnimationFrame(scrollToMenuArea))};
  $("drinkBtn").onclick=()=>{type="beverages";cat="all";$("drinkBtn").classList.add("active");$("foodBtn").classList.remove("active");renderChefSuggestion();renderCats();renderMenu();requestAnimationFrame(()=>requestAnimationFrame(scrollToMenuArea))};
  $("lightboxClose").onclick=()=>{$("imageLightbox").classList.remove("open");document.body.classList.remove("modal-open")};$("imageLightbox").onclick=e=>{if(e.target===$("imageLightbox"))$("lightboxClose").click()};

  await loadFreshData();applyHeader();renderChefSuggestion();renderCats();renderMenu();

  let lastRefresh=0;
  async function refreshFromServer(){const now=Date.now();if(now-lastRefresh<1000)return;lastRefresh=now;const oldScrollX=window.scrollX,oldScrollY=window.scrollY;const oldType=type,oldCat=cat;const ok=await loadFreshData();if(!ok)return;type=oldType;cat=oldCat;const arr=type==="food"?data.food:data.beverages;if(cat!=="all"&&!arr.some(x=>x.available!==false&&x.category===cat))cat="all";$("foodBtn").classList.toggle("active",type==="food");$("drinkBtn").classList.toggle("active",type==="beverages");renderChefSuggestion();renderCats();renderMenu();requestAnimationFrame(()=>window.scrollTo({left:oldScrollX,top:oldScrollY,behavior:"instant"}))}
  window.addEventListener("focus",refreshFromServer);
  document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refreshFromServer()});
})();